---
    version: 1
    disable_existing_loggers: False
    formatters:
      simple:
        format: "%(asctime)s - %(levelname)s - %(name)45s - %(message)s"
    
    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    
      info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ./session/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    
      error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ./session/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    
      custom_file_handler:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: simple
          filename: ./session/deep_learning_sys_conf_info.log
          maxBytes: 10485760 # 10MB
          backupCount: 20
          encoding: utf8
    
    loggers:
      model:
        level: INFO
        handlers: [custom_file_handler]
        propagate: no
    
    root:
      level: INFO
      handlers: [console, info_file_handler, error_file_handler]